jobs:
- job: macOS
  pool:
    vmImage: xcode9-macos10.13
  steps:
    - bash: |
        sudo xcode-select --switch /Applications/Xcode_10.app/Contents/Developer
        brew update
        brew upgrade
        brew tap r-hub/cran
        brew tap-pin r-hub/cran
        brew install autobrew
      displayName: Run brew test

- job: Linux
  pool:
    vmImage: ubuntu-16.04
  steps:
    - bash: |
        sudo apt-get update
        sudo apt remove --purge --auto-remove mono-runtime
        sudo apt-get dist-upgrade
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository -y ppa:marutter/rrutter3.5
        sudo add-apt-repository -y ppa:marutter/c2d4u.5
        sudo apt-get update
        sudo apt-get install -y r-base-dev
      displayName: Run ppa tests

- job: Windows
  pool:
    vmImage: vs2015-win2012r2     
  steps:
    - bash: |
        curl -OL https://cran.r-project.org/bin/windows/base/R-3.5.2-win.exe
      displayName: Run Windows tests
