jobs:
- job: macOS
  pool:
    vmImage: xcode9-macos10.13
  steps:
    - bash: |
        sudo xcode-select --switch /Applications/Xcode_10.app/Contents/Developer
        brew remove $(brew list)
        brew update
        brew upgrade
        brew tap r-hub/cran
        brew tap-pin r-hub/cran
        brew install autobrew
        brew cask install r-app
        R -e "sessionInfo()"
      displayName: Installing R and Autobrew

- job: Linux
  pool:
    vmImage: ubuntu-16.04
  steps:
    - bash: |
        sudo rm /etc/apt/sources.list.d/*
        sudo apt remove --purge --auto-remove mono-runtime
        sudo apt-get update
        sudo apt-get dist-upgrade
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository -y ppa:marutter/rrutter3.5
        sudo add-apt-repository -y ppa:marutter/c2d4u.5
        sudo apt-get update
        sudo apt-get install -y r-base-dev
        R -e "sessionInfo()"
      displayName: Installing R from the PPA

- job: Windows
  pool:
    vmImage: vs2015-win2012r2     
  steps:
    - powershell: |
        Import-Module '.\scripts\appveyor-tool.ps1'
        SetTimezone
        InstallRtools
        InstallR
      displayName: Installing R and Rtools for Windows
